//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSeguridadConJWT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_pagos
    {
        public int id_historial { get; set; }
        public Nullable<int> id_tarjeta { get; set; }
        public string nombre_pago { get; set; }
        public Nullable<int> cantidad_pago { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
    }
}
