//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSeguridadConJWT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public int id_municipio { get; set; }
        public string nombre_municipio { get; set; }
        public Nullable<int> codigo_postal { get; set; }
        public Nullable<int> id_estado { get; set; }
    }
}
