//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSeguridadConJWT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarjeta()
        {
            this.historial_pagos = new HashSet<historial_pagos>();
        }
    
        public int id_tarjeta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> numero_tarjeta { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<int> fecha_experiacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_pagos> historial_pagos { get; set; }
    }
}
